//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int OfficialId { get; set; }
        public int MeetingId { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Official Official { get; set; }
    }
}
